---
name: Publish Docker images

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_REGISTRY_USERNAME: ${{ github.repository_owner }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  push_to_registry:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Github Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login $IMAGE_REGISTRY -u $IMAGE_REGISTRY_USERNAME --password-stdin

      - name: Build and push images
        run: |
          # Get the Dockerfile name with no path
          DOCKERFILES=$(find . -name 'Dockerfile.*' | xargs --max-lines=1 basename)

          echo "
          Building the following Dockerfiles:
          $DOCKERFILES
          "

          for DOCKERFILE in $DOCKERFILES; do

            # Make an image name like: gitworkshop-push-conflict
            IMAGE_NAME=gitworkshop-$(echo $DOCKERFILE | cut -d . -f 2)

            echo "🛠️ Building and pushing an image made from the Dockerfile: $DOCKERFILE"
            docker buildx build \
              --file $DOCKERFILE -t $IMAGE_REGISTRY/$IMAGE_NAME \
              --platform linux/arm64,linux/amd64 \
              --push \
              --tag $FULL_IMAGE_TAG \
              .

          done
