---
name: Publish Docker images

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_REGISTRY_USERNAME: ${{ github.repository_owner }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  push_to_registry:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Github Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login $IMAGE_REGISTRY -u $IMAGE_REGISTRY_USERNAME --password-stdin

      - name: Build and push images
        run: |
          # Get the Dockerfile name with path, without the leading `./`
          # Example: push-conflict/Dockerfile
          DOCKERFILES=$(find . -name Dockerfile | sort | sed 's|^./||')

          echo "
          Building the following Dockerfiles:
          $DOCKERFILES
          "

          for DOCKERFILE in $DOCKERFILES; do

            # Make an image name in the form: gitworkshop-push-conflict
            # If the path to the Dockerfile includes a slash, then it's the common image.
            if echo $DOCKERFILE | grep /; then
              SCENARIO=$(echo $DOCKERFILE | cut -d / -f 1)
              IMAGE_NAME=gitworkshop-$SCENARIO
            else
              IMAGE_NAME=gitworkshop-common
            fi

            TAG=$IMAGE_REGISTRY/$IMAGE_NAME

            echo "
              Building and pushing an image made with:
                🐋 Dockerfile: $DOCKERFILE
                🏷️ Tag:        $TAG
            "

            docker buildx build \
              --file $DOCKERFILE \
              --platform linux/arm64,linux/amd64 \
              --push \
              --tag $TAG \
              .

          done
